name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update apt and install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake pkg-config libgtkmm-4.0-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run tests (if applicable)
        run: |
          # Comandos para ejecutar pruebas, si las tienes

