name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 script:
          - sudo apt update
          - sudo apt install libgtkmm-4.0-dev
jobs:
  build:

    runs-on: ubuntu-latest
    name: Install gtkmm4
   

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
